Traceback (most recent call last):
  File "/Users/eunhyechoe/anaconda3/envs/book/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/eunhyechoe/anaconda3/envs/book/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/eunhyechoe/anaconda3/envs/book/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/eunhyechoe/anaconda3/envs/book/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/eunhyechoe/anaconda3/envs/book/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/eunhyechoe/anaconda3/envs/book/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/eunhyechoe/anaconda3/envs/book/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# cell 1
# Install the neuroboros package
# The '%%capture' is used to suppress the output in the cheatsheet page
%%capture
%pip install -U neuroboros
------------------

----- stderr -----
UsageError: Line magic function `%%capture` not found.
------------------



